# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 0, 141, 41))
        self.label.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label.setObjectName("label")
        self.Calendario = QtWidgets.QCalendarWidget(self.centralwidget)
        self.Calendario.setGeometry(QtCore.QRect(10, 10, 392, 240))
        self.Calendario.setStyleSheet("background-color: rgb(52, 152, 219);\n"
"alternate-background-color: rgb(19, 141, 117);\n"
"selection-color: rgb(255, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.Calendario.setObjectName("Calendario")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 411, 261))
        self.label_4.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(420, 40, 461, 401))
        self.Table.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.Table.setObjectName("Table")
        self.Table.setColumnCount(0)
        self.Table.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 310, 411, 81))
        self.label_5.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.btn_Agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Agregar.setGeometry(QtCore.QRect(30, 310, 41, 51))
        self.btn_Agregar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Imagenes/boton-agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Agregar.setIcon(icon)
        self.btn_Agregar.setIconSize(QtCore.QSize(40, 40))
        self.btn_Agregar.setFlat(True)
        self.btn_Agregar.setObjectName("btn_Agregar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(28, 360, 51, 21))
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 140);")
        self.label_6.setObjectName("label_6")
        self.btn_Modificar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Modificar.setGeometry(QtCore.QRect(130, 310, 41, 51))
        self.btn_Modificar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Imagenes/escribir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Modificar.setIcon(icon1)
        self.btn_Modificar.setIconSize(QtCore.QSize(40, 40))
        self.btn_Modificar.setFlat(True)
        self.btn_Modificar.setObjectName("btn_Modificar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(124, 360, 51, 21))
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 140);")
        self.label_7.setObjectName("label_7")
        self.btn_Eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Eliminar.setGeometry(QtCore.QRect(230, 310, 41, 51))
        self.btn_Eliminar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Imagenes/sustraccion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Eliminar.setIcon(icon2)
        self.btn_Eliminar.setIconSize(QtCore.QSize(40, 40))
        self.btn_Eliminar.setFlat(True)
        self.btn_Eliminar.setObjectName("btn_Eliminar")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(228, 360, 51, 21))
        self.label_8.setStyleSheet("color:rgba(255, 255, 255, 140);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, -10, 491, 451))
        self.label_9.setStyleSheet("background-image: url(./Imagenes/lobo.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.btn_Actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Actualizar.setGeometry(QtCore.QRect(330, 310, 41, 51))
        self.btn_Actualizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./Imagenes/actualizar-flecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Actualizar.setIcon(icon3)
        self.btn_Actualizar.setIconSize(QtCore.QSize(40, 40))
        self.btn_Actualizar.setFlat(True)
        self.btn_Actualizar.setObjectName("btn_Actualizar")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(324, 360, 61, 21))
        self.label_10.setStyleSheet("color:rgba(255, 255, 255, 140);")
        self.label_10.setObjectName("label_10")
        self.label_9.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.Calendario.raise_()
        self.Table.raise_()
        self.label_5.raise_()
        self.btn_Agregar.raise_()
        self.label_6.raise_()
        self.btn_Modificar.raise_()
        self.label_7.raise_()
        self.btn_Eliminar.raise_()
        self.label_8.raise_()
        self.btn_Actualizar.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Calendario</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Agregar"))
        self.label_7.setText(_translate("MainWindow", "Modificar"))
        self.label_8.setText(_translate("MainWindow", "Eliminar"))
        self.label_10.setText(_translate("MainWindow", "Actualizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
